disaster_alert_system/alerts/urls.py
from django.urls import path
from . import views

app_name = 'alerts'

urlpatterns = [
    path('', views.homeAlert, name='homeAlerts'),  # Homepage for alerts
   
    path('add/', views.add_alert, name='add_alert'),
    path('edit/<int:alert_id>/', views.edit_alert, name='edit_alert'),
    path('delete/<int:alert_id>/', views.delete_alert, name='delete_alert'),

]

disaster_alert_system/disaster_alert_system/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views  # Importing the views from users app
from alerts import views as alerts_views  # Importing the views from alerts app
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Handles login, logout, etc.
    path('alerts/', include('alerts.urls')),  # Includes all alert-related URLs
    path('', RedirectView.as_view(url=reverse_lazy('users:landing')), name='root'),
    path('users/', include('users.urls')),  # Make sure this is correct
    path('captcha/', include('captcha.urls')),
# password reset
     path('password-reset/', 
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), 
         name='password_reset'),
    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), 
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), 
         name='password_reset_confirm'),
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
         name='password_reset_complete'),
     

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

disaster_alert_system/users/urls.py
from django.urls import path
from . import views

app_name = 'users'  

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('landing/', views.landing_page, name='landing'),  # Default route
    path('login/', views.login_view, name='login'),  
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('profile/', views.edit_profile, name='edit_profile'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('add-user/', views.add_user, name='add_user'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('contacts/', views.contacts, name='contacts'),
]

disaster_alert_system/users/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField




class Profile(models.Model):
    LOCATION_CHOICES = [
            ('Girne', 'Girne'),
            ('Lefkoşa', 'Lefkoşa'),
            ('Lefke', 'Lefke'),
            ('İskel', 'İskele'),
            ('Gazimağusa', 'Gazimağusa'),
            ('Güzelyurt', 'Güzelyurt'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    location = models.CharField(max_length=50, choices=LOCATION_CHOICES, blank=True , null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

disaster_alert_system/users/forms.py
from django.db import transaction
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from captcha.fields import CaptchaField
from phonenumber_field.formfields import PhoneNumberField
from django.core.validators import RegexValidator
from django.db import transaction
from .models import Profile

class LoginForm(AuthenticationForm):
    captcha = CaptchaField()  # Add CAPTCHA to the login form

# Define the choices for the location dropdown
LOCATION_CHOICES = [
    ('Girne', 'Girne'),
    ('Lefkoşa', 'Lefkoşa'),
    ('Lefke', 'Lefke'),
    ('İskel', 'İskele'),
    ('Gazimağusa', 'Gazimağusa'),
    ('Güzelyurt', 'Güzelyurt'),
]

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    location = forms.ChoiceField(choices=LOCATION_CHOICES, required=True)
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': 'required'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': 'required'})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'location', 'password1', 'password2']

    @transaction.atomic
    def save(self, commit=True):
        # Save the User instance
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        # Get the location value from the form
        location = self.cleaned_data.get('location')

        # Validate location before saving the profile
        if not location:
            raise ValueError("Location field is required.")

        # Create or update the Profile instance
        Profile.objects.update_or_create(
            user=user,
            defaults={'location': location}
        )

        return user

disaster_alert_system/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, LoginForm
from alerts.models import DisasterAlert
from django.shortcuts import get_object_or_404


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()  # The save method in the form now handles everything
            
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')  # Password1 is used for UserCreationForm
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                # Log in the user and set session data
                login(request, user)
                request.session['user_id'] = user.id  # Store user ID in the session

            return redirect('users:home')
        else:
            # Add messages for specific errors if needed
            if 'username' in form.errors:
                messages.error(request, 'Username already exists.')
            if 'password2' in form.errors:
                messages.error(request, 'Passwords do not match.')
            # You can add more custom error handling for other fields as needed
    else:
        form = UserRegisterForm()

    return render(request, 'registration/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # This automatically manages the session
                # Store only the user ID in the session
                request.session['user_id'] = user.id
                return redirect('users:home')
            else:
               messages.error(request, 'Invalid username or password')
        else:
            messages.error(request,'Invalid username or password')            
            form = LoginForm()           
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required
def home(request):
    return render(request, 'home.html')

def landing_page(request):
    return render(request, 'landing.html')


def edit_profile(request):
    if request.method == "POST":
       
        password = request.POST.get("password")
        location = request.POST.get("location")

        user = request.user
       

        if password:
            user.set_password(password)

       
        if hasattr(user, "profile") and location:
            user.profile.location = location
            user.profile.save()

        user.save()

        messages.success(request, "Profile updated successfully!")
        return redirect("users:edit_profile")

    return render(request, "users/edit_profile.html")

def logout_view(request):
    logout(request)
    return redirect('users:landing')

# session 
def profile_view(request):
    user_id = request.session.get('user_id')  # Retrieve the user ID from the session
    if user_id:
        user = User.objects.get(id=user_id)  # Query the database for the user
        return render(request, 'home.html', {'user': user})
    else:
        return redirect('login')  # Redirect if no session exists
    

def password_reset(request):
    return render(request, 'password_reset.html')

def admin_dashboard(request):
    total_users = User.objects.count()
    total_alerts = DisasterAlert.objects.count()
    active_alerts = DisasterAlert.objects.filter(severity='High').count()
    users = User.objects.all()
    alerts = DisasterAlert.objects.all()

    context = {
        'total_users': total_users,
        'total_alerts': total_alerts,
        'active_alerts': active_alerts,
        'users': users,
        'alerts': alerts,
    }
    return render(request, 'users/admin_dashboard.html', context)


def admin_check(user):
    return user.is_staff or user.is_superuser


def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if request.method == "POST":
        user.delete()
        
        return redirect("users:admin_dashboard")

    return render(request, "users/delete_user.html", {"user": user})


def add_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        is_staff = request.POST.get("is_staff") == "on"

        if username and email and password:
            new_user = User.objects.create_user(username=username, email=email, password=password)
            new_user.is_staff = is_staff
            new_user.save()
           
        else:
            messages.error(request, "Please fill in all fields.")

        return redirect("users:admin_dashboard")
    
    return render(request, "users/add_user.html")


def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if request.method == "POST":
        user.username = request.POST.get("username", user.username)
        user.email = request.POST.get("email", user.email)
        password = request.POST.get("password")

        if password:
            user.set_password(password)

        user.is_staff = request.POST.get("is_staff") == "on"
        user.save()

        
        return redirect("users:admin_dashboard")

    return render(request, "users/edit_user.html", {"user": user})



def contacts(request):
    # Sample contact data
    contact_list = [
        
    {"name": "Fire Department", "phone": "199", "email": "firedept@northcyprus.gov"},
    {"name": "Police Department", "phone": "155", "email": "police@northcyprus.gov"},
    {"name": "Medical Emergency", "phone": "112", "email": "ambulance@northcyprus.gov"}


    ]
    return render(request, 'users/contacts.html', {'contacts': contact_list})

disaster_alert_system/users/templates/users/add_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/edit_user.css' %}">
    <title>Add User</title>
</head>
<body>
  
  
  <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" onclick="toggleMenu()">&#9776; Menu</div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"><i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
            <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="#"><i class="bx bx-phone"></i> Contact</a>
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>
    
    <div class="content" id="contentSection">
        
        <form method="post">
            <h2>Add New User</h2>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username" required>
            <br>
            <label for="email">Email:</label>
            <input type="email" name="email" placeholder="Enter Email" required>
            <br>
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter Password" required>
            <br>
            <label for="is_staff">Access to Administration:</label>
            <input type="checkbox" name="is_staff">
            <br>
            <button type="submit">Save Changes</button>
            <a href="{% url 'users:admin_dashboard' %}" class="btn">Cancel</a>
        </form>
        

      </div>
</body>
</html>

disaster_alert_system/users/templates/users/admin_dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Admin Dashboard</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/admin_dashboard.css' %}">
</head>
<body>
    <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" onclick="toggleMenu()">&#9776; Menu</div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"><i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
            <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="{% url 'users:contacts' %}"><i class="bx bx-phone"></i> Contact</a>
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>

    <div class="content" id="contentSection">
        <h1 class="text-center"><strong>Admin Dashboard</strong></h1>
        <div class="dashboard">
            <div class="card">
                <h4>Total Users</h4>
                <p>{{ total_users }}</p>
            </div>
            <div class="card">
                <h4>Total Alerts</h4>
                <p>{{ total_alerts }}</p>
            </div>
            <div class="card">
                <h4>High Severity Alerts</h4>
                <p>{{ active_alerts }}</p>
            </div>
           
        </div>
        <div class="quick-links text-center">
            <a href="{% url 'users:add_user' %}" class="btn">Add New User</a>
            <a href="{% url 'alerts:add_alert' %}" class="btn">Add New Alert</a>
            

        </div>
        <div class="tables-section">
            <div class="tables-container">
                <!-- Users Table -->
                <div class="table-wrapper">
                    <h2> <strong>Users</strong></h2>
                    <table class="styled-table">
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Location</th>
                                <th>Staff</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td>{{ user.username }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.profile.location }}</td>
                                <td>{{ user.is_staff }}</td>
                                <td>
                                    <a href="{% url 'users:edit_user' user.id %}">Edit</a> |
                                    <a href="{% url 'users:delete_user' user.id %}">Delete</a>                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Alerts Table -->
                <div class="table-wrapper">
                    <h2><strong> Alerts</strong></h2>
                    <table class="styled-table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Type</th>
                                
                                <th>Location</th>
                                <th>Date Issued</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for alert in alerts %}
                            <tr>
                                <td>{{ alert.id }}</td>
                                <td>{{ alert.type }}</td>
                                
                                <td>{{ alert.location }}</td>
                                <td>{{ alert.date_issued }}</td>
                                <td>
                                    <a href="{% url 'alerts:edit_alert' alert.id %}">Edit</a> |
                                    <a href="{% url 'alerts:delete_alert' alert.id %}">Delete</a>

                                </td>
                            </tr>
                            {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>


</html>

disaster_alert_system/users/templates/users/contacts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Information</title>
    <link rel="stylesheet" href="{% static 'css/contacts.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
   
</head>

<body>


    <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" onclick="toggleMenu()">
            &#9776; Menu
        </div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"> <i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
            <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="{% url 'users:contacts' %}"><i class="bx bx-phone"></i> Contact</a>
            <!-- New Menu Items -->
    
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>

<div class="content" id="contentSection">
    <div class="contact-container">
        <h1>Emergency Contacts</h1>
        <ul>
            {% for contact in contacts %}
                <li>
                    <h3>{{ contact.name }}</h3>
                    <p>Phone: {{ contact.phone }}</p>
                    <p>Email: <a href="mailto:{{ contact.email }}">{{ contact.email }}</a></p>
                </li>
            {% endfor %}
        </ul>
       
    </div>
</div>
</body>

</html>

disaster_alert_system/users/templates/users/delete_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/edit_user.css' %}">
    <title>Delete User</title>
</head>
<body>
  
  
  <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" onclick="toggleMenu()">&#9776; Menu</div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"><i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
            <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="#"><i class="bx bx-phone"></i> Contact</a>
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>
    
    <div class="content" id="contentSection">
        <form method="post">
            <h2>Delete User account </h2>
            {% csrf_token %}
            <h3>Are you sure you want to delete <strong>{{ user.username }}</strong>'s account?</h3>
            <div class="buttons">
                <button type="submit">Yes, Delete</button>
                <a href="{% url 'users:admin_dashboard' %}" class="btn">Cancel</a>
            </div>
        </form>
        
        
        

      </div>
</body>
</html>

disaster_alert_system/users/templates/users/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    
</head>
<body>
    <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" >
            &#9776; Menu
        </div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"><i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="{% url 'users:contacts' %}"><i class="bx bx-phone"></i> Contact</a>
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>

    <div class="content">
        <div class="profile-container">
            <h2>Edit Your Profile</h2>

            <!-- Display success or error messages -->
            {% if messages %}
                <div id="success-message" class="alert alert-success">
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <p>{{ message }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            <form method="POST" action="{% url 'users:edit_profile' %}">
                {% csrf_token %}

                
                <!-- Password Field -->
                <div class="form-group">
                    <label for="password">New Password:</label>
                    <input type="password" id="password" name="password">
                    <small>Leave empty to keep your current password</small>
                </div>

                <!-- Location Field -->
                <div class="form-group">
                    <label for="location">Current Location:</label>
                    <select id="location" name="location" required>
                        <option value="" disabled {% if not user.profile.location %}selected{% endif %}>Select your location</option>
                        {% for code, name in user.profile.LOCATION_CHOICES %}
                            <option value="{{ code }}" {% if user.profile.location == code %}selected{% endif %}>
                                {{ name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                

                <button type="submit" class="btn-save">Save Changes</button>
            </form>
        </div>
    </div>

    <script>
        // JavaScript to hide the success message after 2 minutes (120000 milliseconds)
        window.addEventListener('DOMContentLoaded', (event) => {
            const message = document.getElementById('success-message');
            if (message) {
                setTimeout(function() {
                    message.style.display = 'none';
                }, 15000); 
            }
        });

        
        
    </script>
</body>
</html>

disaster_alert_system/users/templates/users/edit_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/edit_user.css' %}">
    <title>Edit User</title>
</head>
<body>
  
  
  <div class="menu-container">
        <!-- Menu Icon -->
        <div class="menu-icon" onclick="toggleMenu()">&#9776; Menu</div>
        <!-- Collapsible Menu -->
        <div class="menu-items" id="menuItems">
            <a href="{% url 'users:home' %}"><i class="bx bx-home"></i> Home</a>
            <a href="{% url 'alerts:homeAlerts' %}"><i class='bx bx-error'></i> Alerts</a>
            {% if user.is_staff or user.is_superuser %}
            <a href="{% url 'users:admin_dashboard' %}"><i class='bx bx-user-pin'></i> Administration</a>
            {% endif %}
            <a href="{% url 'users:edit_profile' %}"><i class='bx bx-user'></i> Edit Profile</a>
            <a href="{% url 'users:contacts' %}"><i class="bx bx-phone"></i> Contact</a>
            <a href="{% url 'users:logout' %}"><i class='bx bx-exit'></i> Exit</a>
        </div>
    </div>
    
    <div class="content" id="contentSection">
        
        <br>
        <form method="post">
            <h2>Edit {{ user.username }} Information</h2>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" value="{{ user.username }}" required>
            <br>
            <label for="email">Email:</label>
            <input type="email" name="email" value="{{ user.email }}" required>
            <br>
            <label for="password">Password:</label>
            <input type="password" name="password">
            <small>Leave blank to keep the current password.</small>
            <br>
            <br>
            <label for="is_staff">Access to Administaration : <input type="checkbox" name="is_staff" {% if user.is_staff %}checked{% endif %}></label>
            <br>
            <button type="submit">Save Changes</button>
            <a href="{% url 'users:admin_dashboard' %}" class="btn"> Cancel</a>
            
        </form>
        
        

      </div>
</body>
</html>